# Generated by Django 3.2.6 on 2022-02-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220216_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title', models.CharField(max_length=128, verbose_name='Nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi')),
            ],
            options={
                'verbose_name': "Qo'shimcha hizmat",
                'verbose_name_plural': "Qo'shimcha hizmatlar",
            },
        ),
    ]
